// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/file_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/verizhang/file-manager/internal/service"
)

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockFileService) AbortMultipartUpload(ctx context.Context, req *service.AbortMultipartUploadRequest) (*service.AbortMultipartUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, req)
	ret0, _ := ret[0].(*service.AbortMultipartUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockFileServiceMockRecorder) AbortMultipartUpload(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockFileService)(nil).AbortMultipartUpload), ctx, req)
}

// CompleteMultipartUpload mocks base method.
func (m *MockFileService) CompleteMultipartUpload(ctx context.Context, req *service.CompleteMultipartUploadRequest) (*service.CompleteMultipartUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, req)
	ret0, _ := ret[0].(*service.CompleteMultipartUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockFileServiceMockRecorder) CompleteMultipartUpload(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockFileService)(nil).CompleteMultipartUpload), ctx, req)
}

// CompleteUpload mocks base method.
func (m *MockFileService) CompleteUpload(ctx context.Context, req *service.CompleteUploadRequest) (*service.CompleteUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteUpload", ctx, req)
	ret0, _ := ret[0].(*service.CompleteUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteUpload indicates an expected call of CompleteUpload.
func (mr *MockFileServiceMockRecorder) CompleteUpload(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteUpload", reflect.TypeOf((*MockFileService)(nil).CompleteUpload), ctx, req)
}

// CreateDownloadURL mocks base method.
func (m *MockFileService) CreateDownloadURL(ctx context.Context, req *service.CreateDownloadURLRequest) (*service.CreateDownloadURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDownloadURL", ctx, req)
	ret0, _ := ret[0].(*service.CreateDownloadURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDownloadURL indicates an expected call of CreateDownloadURL.
func (mr *MockFileServiceMockRecorder) CreateDownloadURL(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDownloadURL", reflect.TypeOf((*MockFileService)(nil).CreateDownloadURL), ctx, req)
}

// CreateMultipartUpload mocks base method.
func (m *MockFileService) CreateMultipartUpload(ctx context.Context, req *service.CreateMultipartUploadRequest) (*service.CreateMultipartUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, req)
	ret0, _ := ret[0].(*service.CreateMultipartUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockFileServiceMockRecorder) CreateMultipartUpload(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockFileService)(nil).CreateMultipartUpload), ctx, req)
}

// CreateMultipartUploadUrl mocks base method.
func (m *MockFileService) CreateMultipartUploadUrl(ctx context.Context, req *service.CreateMultipartUploadUrlRequest) (*service.CreateMultipartUploadUrlResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUploadUrl", ctx, req)
	ret0, _ := ret[0].(*service.CreateMultipartUploadUrlResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUploadUrl indicates an expected call of CreateMultipartUploadUrl.
func (mr *MockFileServiceMockRecorder) CreateMultipartUploadUrl(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUploadUrl", reflect.TypeOf((*MockFileService)(nil).CreateMultipartUploadUrl), ctx, req)
}

// CreateUploadUrl mocks base method.
func (m *MockFileService) CreateUploadUrl(ctx context.Context, req *service.CreateUploadRequest) (*service.CreateUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUploadUrl", ctx, req)
	ret0, _ := ret[0].(*service.CreateUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUploadUrl indicates an expected call of CreateUploadUrl.
func (mr *MockFileServiceMockRecorder) CreateUploadUrl(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUploadUrl", reflect.TypeOf((*MockFileService)(nil).CreateUploadUrl), ctx, req)
}

// DeleteFile mocks base method.
func (m *MockFileService) DeleteFile(ctx context.Context, req *service.DeleteFileRequest) (*service.DeleteFileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, req)
	ret0, _ := ret[0].(*service.DeleteFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceMockRecorder) DeleteFile(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileService)(nil).DeleteFile), ctx, req)
}

// GetFile mocks base method.
func (m *MockFileService) GetFile(ctx context.Context, req *service.GetFileRequest) (*service.GetFileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, req)
	ret0, _ := ret[0].(*service.GetFileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockFileServiceMockRecorder) GetFile(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockFileService)(nil).GetFile), ctx, req)
}
