// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	storage "github.com/verizhang/file-manager/internal/storage"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockStorage) AbortMultipartUpload(ctx context.Context, opts storage.AbortMultipartUploadOptions) (*storage.AbortMultipartUploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, opts)
	ret0, _ := ret[0].(*storage.AbortMultipartUploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockStorageMockRecorder) AbortMultipartUpload(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockStorage)(nil).AbortMultipartUpload), ctx, opts)
}

// CompleteMultipartUpload mocks base method.
func (m *MockStorage) CompleteMultipartUpload(ctx context.Context, opts storage.CompleteMultipartUploadOptions) (*storage.CompleteMultipartUploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, opts)
	ret0, _ := ret[0].(*storage.CompleteMultipartUploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockStorageMockRecorder) CompleteMultipartUpload(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockStorage)(nil).CompleteMultipartUpload), ctx, opts)
}

// CreateMultipartUpload mocks base method.
func (m *MockStorage) CreateMultipartUpload(ctx context.Context, opts storage.CreateMultipartUploadOptions) (*storage.CreateMultipartUploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, opts)
	ret0, _ := ret[0].(*storage.CreateMultipartUploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockStorageMockRecorder) CreateMultipartUpload(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockStorage)(nil).CreateMultipartUpload), ctx, opts)
}

// GeneratePresignedMultipartUploadURL mocks base method.
func (m *MockStorage) GeneratePresignedMultipartUploadURL(ctx context.Context, opts storage.GeneratePresignedMultipartUploadURLOptions) (*storage.GeneratePresignedMultipartUploadURLResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedMultipartUploadURL", ctx, opts)
	ret0, _ := ret[0].(*storage.GeneratePresignedMultipartUploadURLResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedMultipartUploadURL indicates an expected call of GeneratePresignedMultipartUploadURL.
func (mr *MockStorageMockRecorder) GeneratePresignedMultipartUploadURL(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedMultipartUploadURL", reflect.TypeOf((*MockStorage)(nil).GeneratePresignedMultipartUploadURL), ctx, opts)
}

// GeneratePresignedUploadURL mocks base method.
func (m *MockStorage) GeneratePresignedUploadURL(ctx context.Context, opts storage.GeneratePresignedUploadURLOptions) (*storage.GeneratePresignedUploadURLResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedUploadURL", ctx, opts)
	ret0, _ := ret[0].(*storage.GeneratePresignedUploadURLResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedUploadURL indicates an expected call of GeneratePresignedUploadURL.
func (mr *MockStorageMockRecorder) GeneratePresignedUploadURL(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedUploadURL", reflect.TypeOf((*MockStorage)(nil).GeneratePresignedUploadURL), ctx, opts)
}

// HeadObject mocks base method.
func (m *MockStorage) HeadObject(ctx context.Context, bucket, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, bucket, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockStorageMockRecorder) HeadObject(ctx, bucket, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockStorage)(nil).HeadObject), ctx, bucket, objectKey)
}
