// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/file_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/verizhang/file-manager/internal/model"
)

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFileRepository) Create(ctx context.Context, file *model.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFileRepositoryMockRecorder) Create(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFileRepository)(nil).Create), ctx, file)
}

// GetByID mocks base method.
func (m *MockFileRepository) GetByID(ctx context.Context, id string) (*model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFileRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFileRepository)(nil).GetByID), ctx, id)
}

// GetByObjectKey mocks base method.
func (m *MockFileRepository) GetByObjectKey(ctx context.Context, objectKey string) (*model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByObjectKey", ctx, objectKey)
	ret0, _ := ret[0].(*model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByObjectKey indicates an expected call of GetByObjectKey.
func (mr *MockFileRepositoryMockRecorder) GetByObjectKey(ctx, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByObjectKey", reflect.TypeOf((*MockFileRepository)(nil).GetByObjectKey), ctx, objectKey)
}

// UpdateStatus mocks base method.
func (m *MockFileRepository) UpdateStatus(ctx context.Context, id string, status model.FileStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFileRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFileRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateStatusAndClearUploadID mocks base method.
func (m *MockFileRepository) UpdateStatusAndClearUploadID(ctx context.Context, id string, status model.FileStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusAndClearUploadID", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusAndClearUploadID indicates an expected call of UpdateStatusAndClearUploadID.
func (mr *MockFileRepositoryMockRecorder) UpdateStatusAndClearUploadID(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusAndClearUploadID", reflect.TypeOf((*MockFileRepository)(nil).UpdateStatusAndClearUploadID), ctx, id, status)
}

// UpdateStatusAndETag mocks base method.
func (m *MockFileRepository) UpdateStatusAndETag(ctx context.Context, id string, status model.FileStatus, etag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusAndETag", ctx, id, status, etag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusAndETag indicates an expected call of UpdateStatusAndETag.
func (mr *MockFileRepositoryMockRecorder) UpdateStatusAndETag(ctx, id, status, etag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusAndETag", reflect.TypeOf((*MockFileRepository)(nil).UpdateStatusAndETag), ctx, id, status, etag)
}
